
# Over-representation analysis





Over-representation test[@boyle2004] is a widely used approach to identify biological themes.
`r Biocpkg("DOSE")` implements hypergeometric model to assess whether the number of selected genes associated with disease is larger than expected.

To determine whether any terms annotate a specified list of genes at frequency greater than that would be expected by chance, `r Biocpkg("DOSE")` calculates a _p_-value using the hypergeometric distribution:

$p = 1 - \displaystyle\sum_{i = 0}^{k-1}\frac{{M \choose i}{{N-M} \choose {n-i}}} {{N \choose n}}$

In this equation, `N` is the total number of genes in the background distribution,
`M` is the number of genes within that distribution that are annotated (either directly or indirectly) to the
node of interest,
`n` is the size of the list of genes of interest and `k` is the number of genes within that list which
are annotated to the node. The background distribution by default is
all the genes that have annotation. User can set the background via `universe` parameter.

_P_-values were adjusted for multiple comparison, and _q_-values were also calculated for FDR control.

