# dplyr verbs for clusterProfiler {#chapter13}

[clusterProfiler.dplyr](https://github.com/YuLab-SMU/clusterProfiler.dplyr) package.


```{r include=F}
library(DOSE)
library(clusterProfiler.dplyr)
library(ggplot2)
library(forcats)
library(enrichplot)
theme_set(theme_grey())
```


```{r}
library(DOSE)
data(geneList)
de = names(geneList)[1:100]
x = enrichDO(de)
```

## filter

```{r}
library(clusterProfiler.dplyr)

filter(x, p.adjust < .05, qvalue < 0.2)
```

## arrange
```{r}
mutate(x, geneRatio = parse_ratio(GeneRatio)) %>%
  arrange(desc(geneRatio))
```

## select

```{r}
select(x, -geneID) %>% head
```

## mutate


```{r dot-richfactor, fig.width=7, fig.height=7}
y <- mutate(x, richFactor = Count / as.numeric(sub("/\\d+", "", BgRatio)))
y

library(ggplot2)
library(forcats)
library(enrichplot)

ggplot(y, showCategory = 20, 
  aes(richFactor, fct_reorder(Description, richFactor))) + 
  geom_segment(aes(xend=0, yend = Description)) +
  geom_point(aes(color=p.adjust, size = Count)) +
  scale_color_viridis_c() +
  scale_size_continuous(range=c(2, 10)) +
  theme_minimal() + 
  xlab("rich factor") +
  ylab(NULL) + 
  ggtitle("Enriched Disease Ontology")
```

## summarise


```{r p-bar, fig.width=8, fig.height=5}
pi=seq(0, 1, length.out=11)

mutate(x, pp = cut(pvalue, pi)) %>%
  group_by(pp) %>% 
  summarise(cnt = n()) %>% 
  ggplot(aes(pp, cnt)) + geom_col() + 
  theme_minimal() +
  xlab("p value intervals") +
  ylab("Frequency") + 
  ggtitle("p value distribution")
```

